### ISSUE TITLE
Encoding error with extended fields syntax [[ ]]

### ISSUE THREAD

**Issue by maximeB** [P1sec/pycrate#35]
# Testing environment:
* pycrate version: 0.3
* python version 2.7.11

# Issue description
The following ASN.1 grammar reproduce the observed bug:
``` ASN.1
World-Schema DEFINITIONS AUTOMATIC TAGS ::= 
BEGIN
  Test ::= SEQUENCE       
  {                                                     
     val1      INTEGER,
	...,
     [[
     ext1	INTEGER OPTIONAL,
     ext2	INTEGER OPTIONAL
     ]]
  }                                                     
END

```
The following code is expected to be able to encode both messages since ext1 and ext2 are optional:
``` python
from example import World_Schema

if __name__ == "__main__":
    msg_ok = {'val1': 1, 'ext1': 2, 'ext2': 3}
    World_Schema.Test.set_val(msg_ok)
    pdu_uper =  World_Schema.Test.to_uper()

    msg_ko = {'val1': 1, 'ext1': 2}
    World_Schema.Test.set_val(msg_ko)
    pdu_uper =  World_Schema.Test.to_uper()
```
Result, it crashes:
``` bash
python test.py
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    World_Schema.Test.set_val(msg_ko)
  File "pycrate-0.3-py2.7.egg/pycrate_asn1rt/asnobj.py", line 631, in set_val
    self._safechk_val(self._val)
  File "pycrate-0.3-py2.7.egg/pycrate_asn1rt/asnobj_construct.py", line 569, in _safechk_val
    self._safechk_valcompl(val)
  File "pycrate-0.3-py2.7.egg/pycrate_asn1rt/asnobj_construct.py", line 584, in _safechk_valcompl
    .format(self.fullname(), val)))
pycrate_asn1rt.err.ASN1ObjErr: Test: missing extended value, {'val1': 1, 'ext1': 2}
```
Both messages can be serialized using [asn1-playground](http://asn1-playground.oss.com/)

**Comment by p1-bmu** [comment]
Thanks for reporting.
A fix is provided in https://github.com/P1sec/pycrate/commit/1f27240777a15c966a40af83f5bd114170125260
Hopefully, the bug was only in the value's filter.
